import newsCard from "../public/news/newscard.svg";
import newsCard1 from "../public/news/diploma.svg";
import latestNews1 from '../public/news/latest1.svg';
import latestNews2 from '../public/news/latest2.svg';
import latestNews3 from '../public/news/latest3.svg';
import trendingNews1 from '../public/news/trendng1.svg';
import trendingNews2 from '../public/news/trending2.svg';
import trendingNews3 from '../public/news/trending3.svg';

import featuredNews1 from '../public/news/featured1.svg';
import featuredNews2 from '../public/news/featured2.svg';
import featuredNews3 from '../public/news/featured3.svg';
export const newsCardDatas = [
  {
    day: "28",
    month: "July",
    year : "2023",
    category :"Latest News",
    title: "Government of India Invites Applications for Diploma Courses ",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard1,
  },
  {
    day: "18",
    month: "July",
    year : "2023",
    category :"Latest News",
    title: "Tech Industry Sees Record Growth",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
  day: "16",
  month: "July",
  year : "2023",
  category:"Latest News",
  title: "Healthcare Innovations in 2024",
  subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
  heading : "About Youth Department",
  passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
  passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
  desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
  picture: latestNews1,
},
  {
    day: "17",
    month: "July",
    year : "2023",
    category: "Trending",
    title: "Retail Industry Adapts to New Trends",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: trendingNews1,
  },
  {
    day: "14",
    month: "July",
    year : "2023",
    category: "Featured",
    title: "Beauty Industry Embraces Natural Products",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: trendingNews2,
  },
  {
    day: "26",
    month: "July",
    year : "2023",
    category: "Featured",
    title: "New Government Youth Skill Training",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    passage2: "New treatments and diagnostics are improving patient outcomes.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: trendingNews3,
  },
  {
    day: "18",
    month: "July",
    year : "2023",
    category: "Trending",
    title: "Tech Industry Sees Record Growth",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
  day: "16",
  month: "July",
  year : "2023",
  category: "Featured",
  title: "Healthcare Innovations in 2024",
  subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
  heading : "About Youth Department",
  passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
  passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
  desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
  picture: featuredNews1,
},
  {
    day: "17",
    month: "July",
    year : "2023",
    category: "Trending",
    title: "Retail Industry Adapts to New Trends",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: trendingNews3,
  },
  {
    day: "14",
    month: "July",
    year : "2023",
    category: "Featured",
    title: "Beauty Industry Embraces Natural Products",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: featuredNews2,
  },
  {
    day: "26",
    month: "July",
    year : "2023",
    category: "Trending",
    title: "New Government Youth Skill Training",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    passage2: "New treatments and diagnostics are improving patient outcomes.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: trendingNews2,
  },
  {
    day: "18",
    month: "June",
    year : "2023",
    category: "Featured",
    title: "Tech Industry Sees Record Growth",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture:featuredNews3,
  },
  {
  day: "16",
  month: "June",
  year : "2023",
  category: "Trending",
  title: "Healthcare Innovations in 2024",
  subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
  heading : "About Youth Department",
  passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
  passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
  desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
  picture: trendingNews2,
},
  {
    day: "03",
    month: "June",
    year : "2023",
    category: "Featured",
    title: "Retail Industry Adapts to New Trends",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: featuredNews1,
  },
  {
    day: "01",
    month: "June",
    year : "2023",
    category: "Trending",
    title: "Beauty Industry Embraces Natural Products",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    passageMain : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.",
    passage1:"The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: trendingNews2,
  },
];
