import newsCard from "../public/news/newscard.svg";
export const newsCardDatas = [
  {
    day: "23",
    month: "July",
    year : "2023",
    lat :"Latest News",
    title: "Government of India Invites Applications for Diploma Courses",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    newsdesc : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
    day: "23",
    month: "July",
    year : "2023",
    lat :"Latest News",
    title: "cant save your eyes",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    newsdesc : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
    day: "23",
    month: "July",
    year : "2023",
    lat :"Latest News",
    title: "Government of India Invites Applications for Diploma Courses",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    newsdesc : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
    day: "23",
    month: "July",
    year : "2023",
    lat :"Latest News",
    title: "Government of India Invites Applications for Diploma Courses",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    newsdesc : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
    day: "23",
    month: "July",
    year : "2023",
    lat :"Latest News",
    title: "nothing last for ever",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    newsdesc : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
  {
    day: "23",
    month: "July",
    year : "2023",
    lat :"Latest News",
    title: "Government of India Invites Applications for Diploma Courses",
    subtitle : "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government ",
    heading : "About Youth Department",
    newsdesc : "The Ministry of Youth Affairs & Sports was initially set up as the Department of Sports in 1982 at the time of organization of the IX Asian Games in New Delhi . Its name was changed to the Department of Youth affairs & sports during celebration of the International Youth Year, 1985. It became a Ministry on 27th May,2000. Subsequently, the Ministry has been bifurcated in Deptt. of Youth Affairs and Deptt. of Sports under two separate Secretaries w.e.f. 30th April,2008. The specific subjects being dealt with by these two Departments are contained in the Order of the Govt. of India (Allocation of Business) Rules, 1961.The Youth, i.e. those falling within the age group of 15-29 years constitutes nearly 40% of the total population of India. This group which is the most vibrant and dynamic segment of the country’s population constitutes potentially its most valuable human resource. To optimally tap their constructive and creative energies, the Department pursues the twin objectives of personality building and nation building, i.e. developing the personality of youth and involving them in various nation-building activities. As most of the issues concerning young people are the functions of other Ministries/Departments, like Education, Employment & Training, Health and Family Welfare, etc. the role of the Ministry of Youth Affairs & Sports is to act as a facilitator and catalytic agent.",
    desc: "Under the Grant-in-Aided Scheme, Government of India invites applications for various Diploma Courses recognized by the Government",
    picture: newsCard,
  },
];
